astrocamp/15th-SyncSquad

Gemfile, app/assets/stylesheets/application.tailwind.css, app/controllers/application_controller.rb, app/controllers/events_controller.rb, app/helpers/events_helper.rb, app/helpers/main_helper.rb, app/models/event.rb, app/models/user.rb
24個可以自動修正：
1個判斷超過120個字：
修正前：
修正後：
=> use rubocop

app/views/layouts/_flash.html.erb, app/views/layouts/_navbar.html.erb, config/locales/en.yml, config/locales/tw.yml
#18 navbar & flash 前端
- 有做 RWD，手機版會有漢堡選單。
- 連結等功能完整一點再調整。
- 會員名稱及信箱會顯示 current_user 的資訊。
- 新增 tw.yml 的 I18N。
- 改成用迴圈顯示所有提醒
https://github.com/astrocamp/15th-SyncSquad/assets/136299906/0b069e19-05b4-43b0-b93d-a85886e3da47
=> Issue/18 navbar & flash 前端

app/javascript/application.js, app/javascript/lib/fontawesome.js, app/javascript/lib/index.js, app/models/user.rb, package.json, yarn.lock
=> Issue/26 安裝 font awesome

app/javascript/controllers/index.js, app/javascript/controllers/reset_form_controller.js, app/views/messages/_new_message_form.html.erb, app/views/rooms/_new_room_form.html.erb
https://github.com/astrocamp/15th-SyncSquad/assets/132726143/cc9e276c-c385-4598-a0b1-56a2e4611b74
=> Issue/30 - 新增建立聊天室或發送訊息後對話框刪除

app/controllers/application_controller.rb, app/controllers/companies_controller.rb, app/controllers/projects_controller.rb, app/controllers/sessions_controller.rb, app/controllers/users/registrations/confirmations_controller.rb, app/controllers/users/registrations/omniauth_callbacks_controller.rb, app/controllers/users/registrations/passwords_controller.rb, app/controllers/users/registrations/registrations_controller.rb, app/controllers/users/registrations/sessions_controller.rb, app/controllers/users/registrations/unlocks_controller.rb, app/controllers/users_controller.rb, app/helpers/companies_helper.rb, app/helpers/sessions_helper.rb, app/helpers/users_helper.rb, app/models/company.rb, app/models/user.rb, app/views/companies/new.html.erb, app/views/companies/sign_in.html.erb, app/views/devise/registrations/new.html.erb, app/views/layouts/_navbar.html.erb, app/views/main/home.html.erb, config/routes.rb, db/migrate/20231225065505_create_companies.rb, db/migrate/20231225201142_add_foreign_key_to_user.rb, db/schema.rb, test/controllers/companies_controller_test.rb, test/controllers/users_controller_test.rb, test/fixtures/companies.yml, test/models/company_test.rb
https://youtu.be/dG5dC4XbuiM
file size太大 所以上傳YT
Company 註冊/登入 + User 創建/登入
User創建 其實就是註冊
接著得做的
1.增加 company註冊後即為登入狀態，現在得註冊後自行手動登入
2.拔掉 user 被註冊後即登入的狀態，因為如果為登入狀態就不能再創建
3.增加 company 忘記密碼功能
4.按了user登出會連同company一起登出的狀況可先忽略，如果第2點完成的話
=> Feat/company(issue/14) Company 註冊/登入 + User 創建/登入

Gemfile.lock, app/controllers/projects_controller.rb, app/javascript/controllers/index.js, app/javascript/controllers/turbomodal_controller.js, app/views/layouts/_navbar.html.erb, app/views/layouts/application.html.erb, app/views/projects/_aside_projects.html.erb, app/views/projects/_form.html.erb, app/views/projects/_main_projects.html.erb, app/views/projects/aside_list.turbo_stream.erb, app/views/projects/create.turbo_stream.erb, app/views/projects/edit.html.erb, app/views/projects/index.html.erb, app/views/projects/main_list.turbo_stream.erb, app/views/projects/new.html.erb, app/views/projects/update.turbo_stream.erb, app/views/shared/_success.html.erb, app/views/shared/_turbomodal.html.erb, package.json, yarn.lock
1. 用 turbo_stream 渲染新增專案的表單 modal。
2. 用 turbo_stream 渲染主要專案列表。
3. 用 turbo_stream 渲染側邊欄專案列表。
4. 用 turbo_stream 渲染編輯專案的表單 modal。
----
藉由turbo_frame+modal
然後用turbo_stream更新事件
https://github.com/astrocamp/15th-SyncSquad/assets/145585863/228de585-95b3-48c2-87ed-09715d5d08f3
先暫時這樣，之後會微調一些東西
=> Issue/28 - Project turbo_stream 版面

app/controllers/events_controller.rb, app/controllers/projects_controller.rb
Project 內使用turbo_stream 將flash 顯現：
https://github.com/astrocamp/15th-SyncSquad/assets/145585863/67106660-d4ed-4574-a175-7b57ed3e96f2
=> Issue 59 - Project: turbo_stream for flash

app/controllers/lists_controller.rb, app/controllers/tasks_controller.rb, app/javascript/lib/fontawesome.js, app/models/user.rb, app/views/events/_listed.html.erb, app/views/events/create.turbo_stream.erb, app/views/events/destroy.turbo_stream.erb, app/views/events/show.html.erb, app/views/events/update.turbo_stream.erb, app/views/lists/create.turbo_stream.erb, app/views/lists/index.html.erb, app/views/lists/new.html.erb, app/views/projects/_form.html.erb, app/views/projects/_list.html.erb, app/views/projects/_main_projects.html.erb, app/views/projects/create.turbo_stream.erb, app/views/projects/index.html.erb, app/views/projects/show.html.erb, app/views/projects/update.turbo_stream.erb, app/views/tasks/create.turbo_stream.erb, app/views/tasks/new.html.erb, yarn.lock
According this issue https://github.com/astrocamp/15th-SyncSquad/issues/55
1. Project 編輯的地方 出現一個 modal + 即時更新
https://github.com/astrocamp/15th-SyncSquad/assets/145585863/879dba0f-49ba-4fd7-8df9-ecdc41bf64b2
2. List 新增的地方 出現一個 modal + 即時更新
https://github.com/astrocamp/15th-SyncSquad/assets/145585863/8dcf7ca5-efda-4aa9-9d28-63d06817f555
3. Task 新增的地方 出現一個 modal + 即時更新
https://github.com/astrocamp/15th-SyncSquad/assets/145585863/a4df773f-57f7-44d5-80de-be262e39fda4
=> Issue/55 - Project show 版面調整 - 1 (new)

app/controllers/companies_controller.rb, app/controllers/hrs_controller.rb, app/controllers/sessions_controller.rb, app/models/user.rb, app/views/companies/new.html.erb, app/views/companies/sign_in.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/hrs/index.html.erb, app/views/main/home.html.erb, config/routes.rb, db/migrate/20231223125308_rename_foreign_keys_in_lists_and_tasks.rb, db/migrate/20231224023000_rename_foreign_key_in_task_responsible_person.rb, db/migrate/20231227060512_fix_lists_and_tasks.rb, db/migrate/20231229022419_change_role_type_in_users.rb, db/schema.rb
功能操作如以下YT影片
[員工登入+登出](https://youtu.be/zYI_6lBFOUU)
[公司註冊+自動登入+登出](https://youtu.be/OQoulU4XZBA)
[公司登入+新增&刪除員工](https://youtu.be/ASO4y40sZ48)
權限還沒設定 #49 
欄位還沒在view #51
=> Issue/50 公司&員工登入 + 新增&刪除員工

app/controllers/application_controller.rb, app/controllers/hrs_controller.rb, app/controllers/lists_controller.rb, app/controllers/projects_controller.rb, app/controllers/tasks_controller.rb, app/models/user.rb, app/views/hrs/index.html.erb, app/views/lists/edit.html.erb, app/views/lists/new.html.erb, app/views/projects/_form.html.erb, app/views/projects/_list.html.erb, app/views/projects/_main_projects.html.erb, app/views/projects/edit.html.erb, app/views/projects/index.html.erb, app/views/projects/new.html.erb, app/views/projects/show.html.erb, app/views/tasks/_task.html.erb, app/views/tasks/edit.html.erb, app/views/tasks/new.html.erb, app/views/tasks/show.html.erb, config/locales/en.yml, config/locales/tw.yml
更新專案管理 view / flash / confirmation
[英文](https://youtu.be/CiAmBZf4LoE)
[中文](https://youtu.be/lzjW3TJnqPQ)
=> Issue/i18n 專案管理i18n

app/views/layouts/_photo_dropdown.html.erb
=> Issue/100 navbar加入會員頭貼

app/assets/stylesheets/application.tailwind.css, app/controllers/comments_controller.rb, app/controllers/tasks_controller.rb, app/javascript/controllers/turbomodal_controller.js, app/models/comment.rb, app/models/task.rb, app/views/comments/create.turbo_stream.erb, app/views/tasks/edit.html.erb, app/views/tasks/new.html.erb, app/views/tasks/show.html.erb, config/locales/en.yml, config/locales/tw.yml, config/routes.rb, db/migrate/20240112074054_create_comments.rb, db/schema.rb
According to this issue: https://github.com/astrocamp/15th-SyncSquad/issues/45
1. 在專案裡的每一個Task底下都可以有留言功能
2. 使用turbo_stream渲染 (create)
3. 留言可以使用markdown語法
https://github.com/astrocamp/15th-SyncSquad/assets/145585863/349dcc5f-e1be-49fc-aee9-2e1565650c0c
=> Issue/45 - Task內的留言功能

app/views/main/home.html.erb, config/locales/en.yml, config/locales/tw.yml
=> issue/71 更正首頁介紹文

app/controllers/projects_controller.rb, app/controllers/tasks_controller.rb, app/helpers/application_helper.rb, app/javascript/controllers/calendar_controller.js, app/javascript/controllers/datepicker_controller.js, app/javascript/controllers/slimselect_controller.js, app/models/order.rb, app/models/task.rb, app/models/user.rb, app/services/line_pay_service.rb, app/views/lists/new.html.erb, app/views/projects/_calendar.html.erb, app/views/projects/_form.html.erb, app/views/projects/new_task.html.erb, app/views/tasks/destroy.turbo_stream.erb, app/views/tasks/edit.html.erb, app/views/tasks/new.html.erb, app/views/tasks/show.html.erb, app/views/tasks/update.turbo_stream.erb, config/locales/en.yml, config/locales/tw.yml, config/routes.rb
According to this issue: https://github.com/astrocamp/15th-SyncSquad/issues/95
A. Tasks 在行事曆上可以移動日期且修改至移動的那天：
1. Tasks可以移動且修改資料
https://github.com/astrocamp/15th-SyncSquad/assets/145585863/b098c1d8-1d4c-42cf-865f-e70ca0436a02
2. 全天的Tasks可以在month Resize 
https://github.com/astrocamp/15th-SyncSquad/assets/145585863/34e1d424-6e9a-4193-a14c-252decc74cf5
3. Tasks可以week Resize 
https://github.com/astrocamp/15th-SyncSquad/assets/145585863/3b1c05da-f941-45ee-b476-889f8df8464e
4. 在week視圖內，移動到all day的話：all day checkbox 要打勾，如果從all day移出來，all day checkbox要取消勾選
https://github.com/astrocamp/15th-SyncSquad/assets/145585863/f53d9ffb-814d-4898-884f-8b131e72a971
B. 編輯以及刪除，可即時更新：
1. 編輯後，即時在行事曆上變更
a. 編輯後，還能新增
b. 編輯後，還能編輯
c. 編輯後，還能刪除
https://github.com/astrocamp/15th-SyncSquad/assets/145585863/644c03ab-3933-46 …
=> Issue/95 - 行事曆

app/javascript/controllers/application.js, app/views/layouts/application.html.erb, app/views/main/home.html.erb, package.json, yarn.lock
According to this https://github.com/astrocamp/15th-SyncSquad/issues/70
1. Add scroll reveal on 3 feature in home page:
https://github.com/astrocamp/15th-SyncSquad/assets/145585863/4db058ff-398e-4ebd-881c-2b6ae1e97c56
=> Issue/70 - add scroll reveal on 3 feature in home page

app/views/tasks/edit.html.erb, app/views/tasks/new.html.erb
According to this: https://github.com/astrocamp/15th-SyncSquad/issues/121
修改專案assign 的人 只容許自己公司的人
https://github.com/astrocamp/15th-SyncSquad/assets/145585863/c70dd43a-c0fb-482a-bee7-bfeba17dcdff
=> Fix: assignment for only company's users

app/controllers/users_controller.rb, app/models/company.rb, app/models/importrecord.rb, app/services/csv_import_users_service.rb, app/views/users/index.html.erb, app/views/users/records.html.erb, config/locales/en.yml, config/locales/tw.yml
According to this https://github.com/astrocamp/15th-SyncSquad/issues/94
1. import紀錄 中英文切換：
https://github.com/astrocamp/15th-SyncSquad/assets/145585863/7bdc2282-b9d4-4e50-bf87-ef7d14a199dd
2. 修正這頁公司只會看到自己公司的紀錄。
-----------
如果還有看到這一大串的在跟我說，雖然我有測過90次，但每次都還是有意想不到的結果
=> Issue/94 - 修正 import紀錄

app/controllers/events_controller.rb, app/javascript/controllers/calendar_controller.js, app/javascript/controllers/event_controller.js, app/javascript/controllers/index.js, app/javascript/lib/fontawesome.js, app/models/company.rb, app/models/event.rb, app/models/user.rb, app/views/events/_form.html.erb, app/views/events/_listed.html.erb, app/views/events/create.turbo_stream.erb, app/views/events/destroy.turbo_stream.erb, app/views/events/edit.html.erb, app/views/events/index.html.erb, app/views/events/new.html.erb, app/views/events/show.html.erb, app/views/events/update.turbo_stream.erb, config/locales/en.yml, config/locales/tw.yml, db/migrate/20240120152115_event_belongs_to_company.rb, db/schema.rb
According to this https://github.com/astrocamp/15th-SyncSquad/issues/126
1. 公司活動的行事曆
進入行事曆要登入公司帳號或員工帳號
https://github.com/astrocamp/15th-SyncSquad/assets/145585863/ab919d74-ebec-42ef-8b15-0b456a6e69f4
2. 只有公司帳號可以 新增刪減， 員工只能看
https://github.com/astrocamp/15th-SyncSquad/assets/145585863/581c69dd-d85b-43b6-8c01-5555f132e534
=> Issue/126 - 公司行事曆

app/controllers/messages_controller.rb, app/controllers/rooms_controller.rb, app/controllers/users_controller.rb, app/models/room.rb, app/models/user.rb, app/policies/room_policy.rb, app/views/shared/_new_group_modal.html.erb, db/schema.rb
1. 恢復聊天室建立
2. 恢復聊天室創建
3. 更新權限設定
- 公司公開聊天室
- 私人群聊只有聊天室成員可以進入
https://github.com/astrocamp/15th-SyncSquad/assets/132726143/c8c8f3a0-c40d-457b-b8e0-9f2cac288fcc
=> Issue/fix chatroom 聊天室權限維修

app/controllers/users/registrations/registrations_controller.rb, app/views/devise/registrations/edit.html.erb, app/views/projects/_head.html.erb, app/views/tasks/_task.html.erb, config/locales/en.yml, config/locales/tw.yml
1. 上傳頭貼後 可以新增專案、列表、任務
2. 員工編輯資料不必再輸入密碼
3. local測試 部署測試 OK
=> Issue/avatar 導覽列、看板、任務 頭貼修復

app/controllers/rooms_controller.rb, app/models/room.rb, app/views/rooms/index.html.erb
According to this:
https://github.com/astrocamp/15th-SyncSquad/issues/147
=> Fix: Public chatroom

app/assets/stylesheets/application.tailwind.css, app/controllers/hrs_controller.rb, app/controllers/users_controller.rb, app/javascript/controllers/calendar_controller.js, app/javascript/controllers/color_picker_controller.js, app/views/hrs/index.html.erb, app/views/lists/_lists.turbo_stream.erb, app/views/lists/edit.html.erb, app/views/lists/new.html.erb, app/views/projects/_aside_projects.html.erb, app/views/projects/_head.html.erb, app/views/projects/_list.html.erb, app/views/projects/_main_projects.html.erb, app/views/projects/calendar.html.erb, app/views/projects/create.turbo_stream.erb, app/views/projects/kanban.html.erb, app/views/projects/update.turbo_stream.erb, app/views/tasks/_task.html.erb, app/views/tasks/edit.html.erb, app/views/tasks/new.html.erb, config/locales/en.yml, config/locales/tw.yml
According to this: https://github.com/astrocamp/15th-SyncSquad/issues/142
1. 建立員工且建立「範例」的專案、列表、任務：
2. 沒有專案時，有提示：
3. hover & 連結 效果: tr 沒有 hover 效果，只有 title hover 會有底線
----------
=> Issue/142 - project & list & task 排版修正

Gemfile, Gemfile.lock, app/controllers/users_controller.rb, app/services/csv_import_users_service.rb, app/views/projects/_head.html.erb, app/views/users/records.html.erb, app/workers/csv_import_worker.rb, config/application.rb, config/locales/en.yml, config/locales/tw.yml, config/routes.rb
https://github.com/astrocamp/15th-SyncSquad/issues/151
=> Issue/151 - Revert without sidekiq

app/assets/stylesheets/application.tailwind.css, app/assets/stylesheets/github.css, app/controllers/rooms_controller.rb, app/controllers/users_controller.rb, app/javascript/controllers/chatroom_list_controller.js, app/javascript/controllers/index.js, app/javascript/controllers/scroll_controller.js, app/javascript/lib/fontawesome.js, app/models/room.rb, app/models/room_visit.rb, app/models/user.rb, app/views/layouts/_single_room.html.erb, app/views/layouts/application.html.erb, app/views/messages/_message.html.erb, app/views/messages/_new_message_form.html.erb, app/views/rooms/_room.html.erb, app/views/rooms/index.html.erb, app/views/shared/_new_group_modal.html.erb, app/views/shared/_new_room_modal.html.erb, app/views/shared/_rooms_list.html.erb, app/views/shared/_users_list.html.erb, app/views/users/_user.html.erb, config/routes.rb, db/migrate/20240121121043_create_room_visits.rb, db/schema.rb, db/seeds.rb
=> Issue/112 聊天室前端切版(RWD、自動捲頁到底、輸入框位置)
